modLoader="javafml"
loaderVersion="${forge_loader_version}"
license="CC0-1.0"
issueTrackerURL="https://github.com/LihvoDruida/RealtimeSync/issues"

[[mods]]
modId="realtime"
version="${version}"
displayName="RealtimeSync"
displayURL="https://github.com/LihvoDruida/RealtimeSync"
logoFile="assets/realtime/icon.png"
authors="melles1991"
description='''Synchronizes Minecraft world time with real system time or a configurable custom day length.'''

[[dependencies.realtime]]
modId="forge"
mandatory=true
versionRange="${forge_loader_version}"
ordering="NONE"
side="BOTH"

[[dependencies.realtime]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
